spring.application.name=team3Project
server.port=8080

# JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MariaDB ??
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/team3project
spring.datasource.username=root
spring.datasource.password=0000
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Thymeleaf
spring.thymeleaf.cache=false

# Devtools - 브라우저 자동 오픈
spring.devtools.livereload.enabled=true